In [1]:
myfunction(firstvar) = 20*firstvar

myfunction (generic function with 1 method)

In [2]:
myfunction(2)

40

In [3]:
myfunction(3.3)

66.0

In [4]:
addxtoy(x,y) = x + y

addxtoy (generic function with 1 method)

In [5]:
addxtoy(1,2)

3

In [6]:
addxtoy(3,-3)

0

In [7]:
function f1(a, b, c)
    a*b+c
end

f1 (generic function with 1 method)

In [9]:
f1(2.0,3,4)

10.0

In [11]:
function showbugprintln(testvar)
    println("insider the showbugprintln")
    println("the type of testvar is $(typeof(testvar)) and the value of testvar is $testvar.")
end

showbugprintln (generic function with 1 method)

In [12]:
a = ['1', 2]
showbugprintln(a)

insider the showbugprintln
the type of testvar is Array{Any,1} and the value of testvar is Any['1', 2].


In [1]:
mycos(x) = cos(x)

mycos (generic function with 1 method)

In [2]:
mycos(.7)

0.7648421872844885

In [3]:
mycos(adj, hyp) = adj/hyp

mycos (generic function with 2 methods)

In [4]:
mycos(12,  13)

0.9230769230769231

In [5]:
methods(mycos)

# 2 methods for generic function "mycos":
[1] mycos(x) in Main at In[1]:1
[2] mycos(adj, hyp) in Main at In[3]:1

In [6]:
mycos(thet::Float64) = cos(thet) # note the use of :: to force julia to check the type

mycos (generic function with 3 methods)

In [1]:
mycos(thet::Float64) = cos(thet)
mycos(hyp, adj)      = adj/hyp

mycos (generic function with 2 methods)

In [2]:
mycos(1)

MethodError: MethodError: no method matching mycos(::Int64)
Closest candidates are:
  mycos(::Any, !Matched::Any) at In[1]:2
  mycos(!Matched::Float64) at In[1]:1

In [3]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


In [4]:
60 \ 5040

84.0

In [5]:
addone(x::Int64) = x+1

addone (generic function with 1 method)

In [6]:
addone(10.)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[5]:1

In [7]:
addone(20*1.0)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[5]:1

In [8]:
addone(10)

11

In [9]:
addone(ceil(1.2)*10)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[5]:1

In [10]:
a,b = 1,2

b = a

a = b

1

In [11]:
a

1

In [12]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [13]:
function add2(x,y) = x + y

LoadError: syntax: unexpected "="

In [14]:
add2(x,y) = return x + y

add2 (generic function with 1 method)

In [15]:
add2(5,7)

12

In [16]:
add22(x,y) = x + y

add22 (generic function with 1 method)

In [17]:
add22(5,7)

12

In [18]:
2^2^3 - 2^4

240

In [19]:
3^2^1^5 + 3^3

36

In [20]:
(2^2)^3 - 2^4

48

In [21]:
println("$(6*6)")

36


In [23]:
(5-7)*2+4

0

In [24]:
1 + 3 < 5 && 2^2 === 4.0

false

In [27]:
(true && false) && (false || true)

false

In [28]:
((true && false) && false) || true

true

In [29]:
true && ((false && false) || true)

true

In [30]:
true && (false && (false || true))

false

In [31]:
matrix = Array{Float64,2}(undef, 3, 2)

3×2 Array{Float64,2}:
 4.94066e-324  1.97626e-323
 9.88131e-324  2.47033e-323
 1.4822e-323   6.9036e-310 

In [32]:
data = [1.6800483  -1.641695388; 
        0.501309281 -0.977697538; 
        1.528012113 0.52771122;
        1.70012253 1.711524991; 
        1.992493625 1.891000015;
        2.706075824 -0.463427794;
        2.994931927 -0.443566619;
        3.491852811 -1.275179133;
        3.501191722 -0.690499597;
        4.459924502 -5.516130799;
        4.936965851 -6.001703074;
        5.023289852 -8.36416901;
        5.04233698 -7.924477517;
        5.50739285 -10.77482371;
        5.568665171 -10.9171878]

15×2 Array{Float64,2}:
 1.68005    -1.6417  
 0.501309   -0.977698
 1.52801     0.527711
 1.70012     1.71152 
 1.99249     1.891   
 2.70608    -0.463428
 2.99493    -0.443567
 3.49185    -1.27518 
 3.50119    -0.6905  
 4.45992    -5.51613 
 4.93697    -6.0017  
 5.02329    -8.36417 
 5.04234    -7.92448 
 5.50739   -10.7748  
 5.56867   -10.9172  

In [33]:
data[:,0]

BoundsError: BoundsError: attempt to access 15×2 Array{Float64,2} at index [Base.Slice(Base.OneTo(15)), 0]

In [34]:
data[:,1]

15-element Array{Float64,1}:
 1.6800483  
 0.501309281
 1.528012113
 1.70012253 
 1.992493625
 2.706075824
 2.994931927
 3.491852811
 3.501191722
 4.459924502
 4.936965851
 5.023289852
 5.04233698 
 5.50739285 
 5.568665171

In [43]:
function f(x)
  return 2x
  3x
end

f (generic function with 1 method)

In [44]:
f(5)

10